apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-alqv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-alqv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-alqv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-alqv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-alqv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hyfk-tenant/rhtap-demo-app/hacbs-test-project-alqv@sha256:b83f8948fb647a41ec1f9767dec660e80ebf963a8dbf2657c4940bda5f0f6fc7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
